### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by havocesp** [Lisiadito/join-lines-plugin#1]
The following link located at "_repo.json_" file is broken, so plugin can't be installed.

[https://github.com/Lisiadito/join-lines-plugin/archive/v1.0.0.zip](https://github.com/Lisiadito/join-lines-plugin/archive/v1.0.0.zip)

**Comment by Lisiadito** [comment]
Thanks for opening this issue. I will have a look into that.

**Comment by Lisiadito** [comment]
@havocesp I fixed it. Can you verify that you can install the plugin please?
