### ISSUE TITLE
Removes indentation of the current line

### ISSUE THREAD

**Issue by allanderek** [Lisiadito/join-lines-plugin#2]
If you use joinLines to join the current and the next line, it removes most of the indentation from the current line, which is probably not what you want, particularly when editing code.

So for example:

```
       x =
              y
```
becomes
```
 x = y
```
when you probably wanted

```
       x = y
```
This happens because line 38 reduces *all* whitespace to a single space character:
```
    local modifiedSelection = string.gsub(selection, "%s+", " ")
```
This also means that if you have deliberate whitespace within a line it gets squased eg.
```
x:          blah;
y:           foo
                 + bar; 
```
if joining the `y:` line to the one below you get:
```
x:          blah;
y: foo + bar;
```

Both issues can be solved by requiring the replaced whitespace to start with a new line:

```
    local modifiedSelection = string.gsub(selection, "\n%s+", " ")
```

**Comment by Lisiadito** [comment]
Thanks for opening this issue. You're absolutely right. It makes sense to keep the indentation. Do you want to fix this and open a PR?

**Comment by Lisiadito** [comment]
Closing this due to merge of #3
